name: MSYS2

on:
  push:
  pull_request:

jobs:


  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        task: [ true, false ]
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        release: ${{ matrix.task }}
        update: true
        install: base-devel git gcc

    - uses: actions/checkout@v2

    - run: gcc --version


  ref:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        update: [ true, false ]
        release: [ true, false ]
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        release: ${{ matrix.release }}
        update: ${{ matrix.update }}

    - run: |
        sed -i 's/^CheckSpace/#CheckSpace/g' C:/msys64/etc/pacman.conf

    - run: |
        pacman -Sy --noconfirm --noprogressbar --needed pacman-mirrors

    - run: |
        pacman -Sy --nodeps --noconfirm --noprogressbar --needed  mingw-w64-x86_64-binutils mingw-w64-x86_64-crt mingw-w64-x86_64-dlfcn mingw-w64-x86_64-headers mingw-w64-x86_64-libiconv mingw-w64-x86_64-isl mingw-w64-x86_64-make mingw-w64-x86_64-mpc mingw-w64-x86_64-mpfr mingw-w64-x86_64-windows-default-manifest mingw-w64-x86_64-libwinpthread mingw-w64-x86_64-libyaml mingw-w64-x86_64-winpthreads mingw-w64-x86_64-zlib mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-gcc

    - run: |
        pacman -S --noconfirm --noprogressbar --needed  mingw-w64-x86_64-gdbm mingw-w64-x86_64-gmp mingw-w64-x86_64-libffi mingw-w64-x86_64-libyaml mingw-w64-x86_64-openssl mingw-w64-x86_64-ragel mingw-w64-x86_64-readline automake1.16 bison

    - run: |
        gcc --version
